// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: dfs.proto

package dfspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ClientId      int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateFileRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *CreateFileRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type CreateFileResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Success       bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClientId      int64                     `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Stripes       map[int32]*StripeMetadata `protobuf:"bytes,3,rep,name=stripes,proto3" json:"stripes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateFileResponse) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateFileResponse) GetStripes() map[int32]*StripeMetadata {
	if x != nil {
		return x.Stripes
	}
	return nil
}

type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateChunkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AllocateChunkRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type ChunkList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIds      []string               `protobuf:"bytes,1,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkList) Reset() {
	*x = ChunkList{}
	mi := &file_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkList) ProtoMessage() {}

func (x *ChunkList) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkList.ProtoReflect.Descriptor instead.
func (*ChunkList) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkList) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

type StripeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StripeNum     int32                  `protobuf:"varint,1,opt,name=stripe_num,json=stripeNum,proto3" json:"stripe_num,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"` // [data1, data2, parity]
	Servers       []string               `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`                   // [server1, server2, server3]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StripeMetadata) Reset() {
	*x = StripeMetadata{}
	mi := &file_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StripeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StripeMetadata) ProtoMessage() {}

func (x *StripeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StripeMetadata.ProtoReflect.Descriptor instead.
func (*StripeMetadata) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *StripeMetadata) GetStripeNum() int32 {
	if x != nil {
		return x.StripeNum
	}
	return 0
}

func (x *StripeMetadata) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *StripeMetadata) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type AllocateChunkResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Stripes       map[int32]*StripeMetadata `protobuf:"bytes,1,rep,name=stripes,proto3" json:"stripes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkResponse) Reset() {
	*x = AllocateChunkResponse{}
	mi := &file_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkResponse) ProtoMessage() {}

func (x *AllocateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *AllocateChunkResponse) GetStripes() map[int32]*StripeMetadata {
	if x != nil {
		return x.Stripes
	}
	return nil
}

type GetFileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataRequest) Reset() {
	*x = GetFileMetadataRequest{}
	mi := &file_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRequest) ProtoMessage() {}

func (x *GetFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileMetadataRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetFileMetadataRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetFileMetadataResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Stripes       map[int32]*StripeMetadata `protobuf:"bytes,1,rep,name=stripes,proto3" json:"stripes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FileSize      int64                     `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataResponse) Reset() {
	*x = GetFileMetadataResponse{}
	mi := &file_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataResponse) ProtoMessage() {}

func (x *GetFileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetFileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileMetadataResponse) GetStripes() map[int32]*StripeMetadata {
	if x != nil {
		return x.Stripes
	}
	return nil
}

func (x *GetFileMetadataResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type WriteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkRequest) Reset() {
	*x = WriteChunkRequest{}
	mi := &file_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkRequest) ProtoMessage() {}

func (x *WriteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkRequest.ProtoReflect.Descriptor instead.
func (*WriteChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *WriteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *WriteChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteChunkRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *WriteChunkRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type WriteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkResponse) Reset() {
	*x = WriteChunkResponse{}
	mi := &file_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkResponse) ProtoMessage() {}

func (x *WriteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkResponse.ProtoReflect.Descriptor instead.
func (*WriteChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *WriteChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRequest) Reset() {
	*x = ReadChunkRequest{}
	mi := &file_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRequest) ProtoMessage() {}

func (x *ReadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *ReadChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReadChunkRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type ReadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkResponse) Reset() {
	*x = ReadChunkResponse{}
	mi := &file_dfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkResponse) ProtoMessage() {}

func (x *ReadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{11}
}

func (x *ReadChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadChunkResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ForwardChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	NextLocations []string               `protobuf:"bytes,3,rep,name=next_locations,json=nextLocations,proto3" json:"next_locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardChunkRequest) Reset() {
	*x = ForwardChunkRequest{}
	mi := &file_dfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardChunkRequest) ProtoMessage() {}

func (x *ForwardChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardChunkRequest.ProtoReflect.Descriptor instead.
func (*ForwardChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{12}
}

func (x *ForwardChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ForwardChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ForwardChunkRequest) GetNextLocations() []string {
	if x != nil {
		return x.NextLocations
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_dfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_dfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{14}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"` // Chunks this server currently has
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryRequest) Reset() {
	*x = InventoryRequest{}
	mi := &file_dfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRequest) ProtoMessage() {}

func (x *InventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRequest.ProtoReflect.Descriptor instead.
func (*InventoryRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{15}
}

func (x *InventoryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *InventoryRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

type ReconstructionTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`                     // The missing chunk to reconstruct
	StripeNum     int32                  `protobuf:"varint,2,opt,name=stripe_num,json=stripeNum,proto3" json:"stripe_num,omitempty"`              // Stripe number
	OtherChunkIds []string               `protobuf:"bytes,3,rep,name=other_chunk_ids,json=otherChunkIds,proto3" json:"other_chunk_ids,omitempty"` // [chunk1, chunk2] - the 2 available chunks
	OtherServers  []string               `protobuf:"bytes,4,rep,name=other_servers,json=otherServers,proto3" json:"other_servers,omitempty"`      // [server1, server2] - where to get them
	ClientId      int64                  `protobuf:"varint,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                 // Client ID for physical isolation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconstructionTask) Reset() {
	*x = ReconstructionTask{}
	mi := &file_dfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconstructionTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconstructionTask) ProtoMessage() {}

func (x *ReconstructionTask) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconstructionTask.ProtoReflect.Descriptor instead.
func (*ReconstructionTask) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{16}
}

func (x *ReconstructionTask) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReconstructionTask) GetStripeNum() int32 {
	if x != nil {
		return x.StripeNum
	}
	return 0
}

func (x *ReconstructionTask) GetOtherChunkIds() []string {
	if x != nil {
		return x.OtherChunkIds
	}
	return nil
}

func (x *ReconstructionTask) GetOtherServers() []string {
	if x != nil {
		return x.OtherServers
	}
	return nil
}

func (x *ReconstructionTask) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type InventoryResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MissingChunks       []string               `protobuf:"bytes,1,rep,name=missing_chunks,json=missingChunks,proto3" json:"missing_chunks,omitempty"`                   // Chunks to reconstruct
	ExtraChunks         []string               `protobuf:"bytes,2,rep,name=extra_chunks,json=extraChunks,proto3" json:"extra_chunks,omitempty"`                         // Chunks to delete (orphaned)
	ReconstructionTasks []*ReconstructionTask  `protobuf:"bytes,3,rep,name=reconstruction_tasks,json=reconstructionTasks,proto3" json:"reconstruction_tasks,omitempty"` // How to reconstruct missing chunks
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_dfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{17}
}

func (x *InventoryResponse) GetMissingChunks() []string {
	if x != nil {
		return x.MissingChunks
	}
	return nil
}

func (x *InventoryResponse) GetExtraChunks() []string {
	if x != nil {
		return x.ExtraChunks
	}
	return nil
}

func (x *InventoryResponse) GetReconstructionTasks() []*ReconstructionTask {
	if x != nil {
		return x.ReconstructionTasks
	}
	return nil
}

type ConfirmWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmWriteRequest) Reset() {
	*x = ConfirmWriteRequest{}
	mi := &file_dfs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmWriteRequest) ProtoMessage() {}

func (x *ConfirmWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmWriteRequest.ProtoReflect.Descriptor instead.
func (*ConfirmWriteRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{18}
}

func (x *ConfirmWriteRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConfirmWriteRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

type ConfirmWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmWriteResponse) Reset() {
	*x = ConfirmWriteResponse{}
	mi := &file_dfs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmWriteResponse) ProtoMessage() {}

func (x *ConfirmWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmWriteResponse.ProtoReflect.Descriptor instead.
func (*ConfirmWriteResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{19}
}

func (x *ConfirmWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_dfs_proto protoreflect.FileDescriptor

const file_dfs_proto_rawDesc = "" +
	"\n" +
	"\tdfs.proto\x12\x05dfspb\"k\n" +
	"\x11CreateFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\"\xe0\x01\n" +
	"\x12CreateFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12@\n" +
	"\astripes\x18\x03 \x03(\v2&.dfspb.CreateFileResponse.StripesEntryR\astripes\x1aQ\n" +
	"\fStripesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.dfspb.StripeMetadataR\x05value:\x028\x01\"O\n" +
	"\x14AllocateChunkRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\"(\n" +
	"\tChunkList\x12\x1b\n" +
	"\tchunk_ids\x18\x01 \x03(\tR\bchunkIds\"f\n" +
	"\x0eStripeMetadata\x12\x1d\n" +
	"\n" +
	"stripe_num\x18\x01 \x01(\x05R\tstripeNum\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\x12\x18\n" +
	"\aservers\x18\x03 \x03(\tR\aservers\"\xaf\x01\n" +
	"\x15AllocateChunkResponse\x12C\n" +
	"\astripes\x18\x01 \x03(\v2).dfspb.AllocateChunkResponse.StripesEntryR\astripes\x1aQ\n" +
	"\fStripesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.dfspb.StripeMetadataR\x05value:\x028\x01\"Q\n" +
	"\x16GetFileMetadataRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\"\xd0\x01\n" +
	"\x17GetFileMetadataResponse\x12E\n" +
	"\astripes\x18\x01 \x03(\v2+.dfspb.GetFileMetadataResponse.StripesEntryR\astripes\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x1aQ\n" +
	"\fStripesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.dfspb.StripeMetadataR\x05value:\x028\x01\"{\n" +
	"\x11WriteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\".\n" +
	"\x12WriteChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x10ReadChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\"C\n" +
	"\x11ReadChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\"k\n" +
	"\x13ForwardChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12%\n" +
	"\x0enext_locations\x18\x03 \x03(\tR\rnextLocations\",\n" +
	"\x10HeartbeatRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x10InventoryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\"\xb8\x01\n" +
	"\x12ReconstructionTask\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1d\n" +
	"\n" +
	"stripe_num\x18\x02 \x01(\x05R\tstripeNum\x12&\n" +
	"\x0fother_chunk_ids\x18\x03 \x03(\tR\rotherChunkIds\x12#\n" +
	"\rother_servers\x18\x04 \x03(\tR\fotherServers\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\x03R\bclientId\"\xab\x01\n" +
	"\x11InventoryResponse\x12%\n" +
	"\x0emissing_chunks\x18\x01 \x03(\tR\rmissingChunks\x12!\n" +
	"\fextra_chunks\x18\x02 \x03(\tR\vextraChunks\x12L\n" +
	"\x14reconstruction_tasks\x18\x03 \x03(\v2\x19.dfspb.ReconstructionTaskR\x13reconstructionTasks\"N\n" +
	"\x13ConfirmWriteRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\"0\n" +
	"\x14ConfirmWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc5\x03\n" +
	"\fMasterServer\x12A\n" +
	"\n" +
	"CreateFile\x12\x18.dfspb.CreateFileRequest\x1a\x19.dfspb.CreateFileResponse\x12J\n" +
	"\rAllocateChunk\x12\x1b.dfspb.AllocateChunkRequest\x1a\x1c.dfspb.AllocateChunkResponse\x12P\n" +
	"\x0fGetFileMetadata\x12\x1d.dfspb.GetFileMetadataRequest\x1a\x1e.dfspb.GetFileMetadataResponse\x12E\n" +
	"\x10ReceiveHeartbeat\x12\x17.dfspb.HeartbeatRequest\x1a\x18.dfspb.HeartbeatResponse\x12D\n" +
	"\x0fReportInventory\x12\x17.dfspb.InventoryRequest\x1a\x18.dfspb.InventoryResponse\x12G\n" +
	"\fConfirmWrite\x12\x1a.dfspb.ConfirmWriteRequest\x1a\x1b.dfspb.ConfirmWriteResponse2\xd7\x01\n" +
	"\vChunkServer\x12A\n" +
	"\n" +
	"WriteChunk\x12\x18.dfspb.WriteChunkRequest\x1a\x19.dfspb.WriteChunkResponse\x12>\n" +
	"\tReadChunk\x12\x17.dfspb.ReadChunkRequest\x1a\x18.dfspb.ReadChunkResponse\x12E\n" +
	"\fForwardChunk\x12\x1a.dfspb.ForwardChunkRequest\x1a\x19.dfspb.WriteChunkResponseB\x13Z\x11dfs-project/dfspbb\x06proto3"

var (
	file_dfs_proto_rawDescOnce sync.Once
	file_dfs_proto_rawDescData []byte
)

func file_dfs_proto_rawDescGZIP() []byte {
	file_dfs_proto_rawDescOnce.Do(func() {
		file_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)))
	})
	return file_dfs_proto_rawDescData
}

var file_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_dfs_proto_goTypes = []any{
	(*CreateFileRequest)(nil),       // 0: dfspb.CreateFileRequest
	(*CreateFileResponse)(nil),      // 1: dfspb.CreateFileResponse
	(*AllocateChunkRequest)(nil),    // 2: dfspb.AllocateChunkRequest
	(*ChunkList)(nil),               // 3: dfspb.ChunkList
	(*StripeMetadata)(nil),          // 4: dfspb.StripeMetadata
	(*AllocateChunkResponse)(nil),   // 5: dfspb.AllocateChunkResponse
	(*GetFileMetadataRequest)(nil),  // 6: dfspb.GetFileMetadataRequest
	(*GetFileMetadataResponse)(nil), // 7: dfspb.GetFileMetadataResponse
	(*WriteChunkRequest)(nil),       // 8: dfspb.WriteChunkRequest
	(*WriteChunkResponse)(nil),      // 9: dfspb.WriteChunkResponse
	(*ReadChunkRequest)(nil),        // 10: dfspb.ReadChunkRequest
	(*ReadChunkResponse)(nil),       // 11: dfspb.ReadChunkResponse
	(*ForwardChunkRequest)(nil),     // 12: dfspb.ForwardChunkRequest
	(*HeartbeatRequest)(nil),        // 13: dfspb.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 14: dfspb.HeartbeatResponse
	(*InventoryRequest)(nil),        // 15: dfspb.InventoryRequest
	(*ReconstructionTask)(nil),      // 16: dfspb.ReconstructionTask
	(*InventoryResponse)(nil),       // 17: dfspb.InventoryResponse
	(*ConfirmWriteRequest)(nil),     // 18: dfspb.ConfirmWriteRequest
	(*ConfirmWriteResponse)(nil),    // 19: dfspb.ConfirmWriteResponse
	nil,                             // 20: dfspb.CreateFileResponse.StripesEntry
	nil,                             // 21: dfspb.AllocateChunkResponse.StripesEntry
	nil,                             // 22: dfspb.GetFileMetadataResponse.StripesEntry
}
var file_dfs_proto_depIdxs = []int32{
	20, // 0: dfspb.CreateFileResponse.stripes:type_name -> dfspb.CreateFileResponse.StripesEntry
	21, // 1: dfspb.AllocateChunkResponse.stripes:type_name -> dfspb.AllocateChunkResponse.StripesEntry
	22, // 2: dfspb.GetFileMetadataResponse.stripes:type_name -> dfspb.GetFileMetadataResponse.StripesEntry
	16, // 3: dfspb.InventoryResponse.reconstruction_tasks:type_name -> dfspb.ReconstructionTask
	4,  // 4: dfspb.CreateFileResponse.StripesEntry.value:type_name -> dfspb.StripeMetadata
	4,  // 5: dfspb.AllocateChunkResponse.StripesEntry.value:type_name -> dfspb.StripeMetadata
	4,  // 6: dfspb.GetFileMetadataResponse.StripesEntry.value:type_name -> dfspb.StripeMetadata
	0,  // 7: dfspb.MasterServer.CreateFile:input_type -> dfspb.CreateFileRequest
	2,  // 8: dfspb.MasterServer.AllocateChunk:input_type -> dfspb.AllocateChunkRequest
	6,  // 9: dfspb.MasterServer.GetFileMetadata:input_type -> dfspb.GetFileMetadataRequest
	13, // 10: dfspb.MasterServer.ReceiveHeartbeat:input_type -> dfspb.HeartbeatRequest
	15, // 11: dfspb.MasterServer.ReportInventory:input_type -> dfspb.InventoryRequest
	18, // 12: dfspb.MasterServer.ConfirmWrite:input_type -> dfspb.ConfirmWriteRequest
	8,  // 13: dfspb.ChunkServer.WriteChunk:input_type -> dfspb.WriteChunkRequest
	10, // 14: dfspb.ChunkServer.ReadChunk:input_type -> dfspb.ReadChunkRequest
	12, // 15: dfspb.ChunkServer.ForwardChunk:input_type -> dfspb.ForwardChunkRequest
	1,  // 16: dfspb.MasterServer.CreateFile:output_type -> dfspb.CreateFileResponse
	5,  // 17: dfspb.MasterServer.AllocateChunk:output_type -> dfspb.AllocateChunkResponse
	7,  // 18: dfspb.MasterServer.GetFileMetadata:output_type -> dfspb.GetFileMetadataResponse
	14, // 19: dfspb.MasterServer.ReceiveHeartbeat:output_type -> dfspb.HeartbeatResponse
	17, // 20: dfspb.MasterServer.ReportInventory:output_type -> dfspb.InventoryResponse
	19, // 21: dfspb.MasterServer.ConfirmWrite:output_type -> dfspb.ConfirmWriteResponse
	9,  // 22: dfspb.ChunkServer.WriteChunk:output_type -> dfspb.WriteChunkResponse
	11, // 23: dfspb.ChunkServer.ReadChunk:output_type -> dfspb.ReadChunkResponse
	9,  // 24: dfspb.ChunkServer.ForwardChunk:output_type -> dfspb.WriteChunkResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dfs_proto_init() }
func file_dfs_proto_init() {
	if File_dfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dfs_proto_goTypes,
		DependencyIndexes: file_dfs_proto_depIdxs,
		MessageInfos:      file_dfs_proto_msgTypes,
	}.Build()
	File_dfs_proto = out.File
	file_dfs_proto_goTypes = nil
	file_dfs_proto_depIdxs = nil
}
