// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: dfs.proto

package dfspb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterServer_CreateFile_FullMethodName        = "/dfspb.MasterServer/CreateFile"
	MasterServer_AllocateChunk_FullMethodName     = "/dfspb.MasterServer/AllocateChunk"
	MasterServer_GetFileMetadata_FullMethodName   = "/dfspb.MasterServer/GetFileMetadata"
	MasterServer_ReceiveHeartbeat_FullMethodName  = "/dfspb.MasterServer/ReceiveHeartbeat"
	MasterServer_ReportInventory_FullMethodName   = "/dfspb.MasterServer/ReportInventory"
	MasterServer_ConfirmWrite_FullMethodName      = "/dfspb.MasterServer/ConfirmWrite"
	MasterServer_DeleteFile_FullMethodName        = "/dfspb.MasterServer/DeleteFile"
	MasterServer_ListFiles_FullMethodName         = "/dfspb.MasterServer/ListFiles"
	MasterServer_GetActiveMaster_FullMethodName   = "/dfspb.MasterServer/GetActiveMaster"
	MasterServer_CreateFolder_FullMethodName      = "/dfspb.MasterServer/CreateFolder"
	MasterServer_DeleteFolder_FullMethodName      = "/dfspb.MasterServer/DeleteFolder"
	MasterServer_MoveFile_FullMethodName          = "/dfspb.MasterServer/MoveFile"
	MasterServer_ListFilesDetailed_FullMethodName = "/dfspb.MasterServer/ListFilesDetailed"
	MasterServer_ReadFileContent_FullMethodName   = "/dfspb.MasterServer/ReadFileContent"
)

// MasterServerClient is the client API for MasterServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterServerClient interface {
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	AllocateChunk(ctx context.Context, in *AllocateChunkRequest, opts ...grpc.CallOption) (*AllocateChunkResponse, error)
	GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*GetFileMetadataResponse, error)
	ReceiveHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportInventory(ctx context.Context, in *InventoryRequest, opts ...grpc.CallOption) (*InventoryResponse, error)
	ConfirmWrite(ctx context.Context, in *ConfirmWriteRequest, opts ...grpc.CallOption) (*ConfirmWriteResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	GetActiveMaster(ctx context.Context, in *GetActiveMasterRequest, opts ...grpc.CallOption) (*GetActiveMasterResponse, error)
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error)
	DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error)
	MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*MoveFileResponse, error)
	ListFilesDetailed(ctx context.Context, in *ListFilesDetailedRequest, opts ...grpc.CallOption) (*ListFilesDetailedResponse, error)
	ReadFileContent(ctx context.Context, in *ReadFileContentRequest, opts ...grpc.CallOption) (*ReadFileContentResponse, error)
}

type masterServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServerClient(cc grpc.ClientConnInterface) MasterServerClient {
	return &masterServerClient{cc}
}

func (c *masterServerClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, MasterServer_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) AllocateChunk(ctx context.Context, in *AllocateChunkRequest, opts ...grpc.CallOption) (*AllocateChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateChunkResponse)
	err := c.cc.Invoke(ctx, MasterServer_AllocateChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*GetFileMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileMetadataResponse)
	err := c.cc.Invoke(ctx, MasterServer_GetFileMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) ReceiveHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MasterServer_ReceiveHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) ReportInventory(ctx context.Context, in *InventoryRequest, opts ...grpc.CallOption) (*InventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResponse)
	err := c.cc.Invoke(ctx, MasterServer_ReportInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) ConfirmWrite(ctx context.Context, in *ConfirmWriteRequest, opts ...grpc.CallOption) (*ConfirmWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmWriteResponse)
	err := c.cc.Invoke(ctx, MasterServer_ConfirmWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, MasterServer_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, MasterServer_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) GetActiveMaster(ctx context.Context, in *GetActiveMasterRequest, opts ...grpc.CallOption) (*GetActiveMasterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveMasterResponse)
	err := c.cc.Invoke(ctx, MasterServer_GetActiveMaster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderResponse)
	err := c.cc.Invoke(ctx, MasterServer_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFolderResponse)
	err := c.cc.Invoke(ctx, MasterServer_DeleteFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*MoveFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveFileResponse)
	err := c.cc.Invoke(ctx, MasterServer_MoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) ListFilesDetailed(ctx context.Context, in *ListFilesDetailedRequest, opts ...grpc.CallOption) (*ListFilesDetailedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesDetailedResponse)
	err := c.cc.Invoke(ctx, MasterServer_ListFilesDetailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServerClient) ReadFileContent(ctx context.Context, in *ReadFileContentRequest, opts ...grpc.CallOption) (*ReadFileContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileContentResponse)
	err := c.cc.Invoke(ctx, MasterServer_ReadFileContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServerServer is the server API for MasterServer service.
// All implementations must embed UnimplementedMasterServerServer
// for forward compatibility.
type MasterServerServer interface {
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	AllocateChunk(context.Context, *AllocateChunkRequest) (*AllocateChunkResponse, error)
	GetFileMetadata(context.Context, *GetFileMetadataRequest) (*GetFileMetadataResponse, error)
	ReceiveHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportInventory(context.Context, *InventoryRequest) (*InventoryResponse, error)
	ConfirmWrite(context.Context, *ConfirmWriteRequest) (*ConfirmWriteResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	GetActiveMaster(context.Context, *GetActiveMasterRequest) (*GetActiveMasterResponse, error)
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error)
	DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error)
	MoveFile(context.Context, *MoveFileRequest) (*MoveFileResponse, error)
	ListFilesDetailed(context.Context, *ListFilesDetailedRequest) (*ListFilesDetailedResponse, error)
	ReadFileContent(context.Context, *ReadFileContentRequest) (*ReadFileContentResponse, error)
	mustEmbedUnimplementedMasterServerServer()
}

// UnimplementedMasterServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterServerServer struct{}

func (UnimplementedMasterServerServer) CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedMasterServerServer) AllocateChunk(context.Context, *AllocateChunkRequest) (*AllocateChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateChunk not implemented")
}
func (UnimplementedMasterServerServer) GetFileMetadata(context.Context, *GetFileMetadataRequest) (*GetFileMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedMasterServerServer) ReceiveHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveHeartbeat not implemented")
}
func (UnimplementedMasterServerServer) ReportInventory(context.Context, *InventoryRequest) (*InventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportInventory not implemented")
}
func (UnimplementedMasterServerServer) ConfirmWrite(context.Context, *ConfirmWriteRequest) (*ConfirmWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmWrite not implemented")
}
func (UnimplementedMasterServerServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedMasterServerServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedMasterServerServer) GetActiveMaster(context.Context, *GetActiveMasterRequest) (*GetActiveMasterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveMaster not implemented")
}
func (UnimplementedMasterServerServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedMasterServerServer) DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFolder not implemented")
}
func (UnimplementedMasterServerServer) MoveFile(context.Context, *MoveFileRequest) (*MoveFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveFile not implemented")
}
func (UnimplementedMasterServerServer) ListFilesDetailed(context.Context, *ListFilesDetailedRequest) (*ListFilesDetailedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFilesDetailed not implemented")
}
func (UnimplementedMasterServerServer) ReadFileContent(context.Context, *ReadFileContentRequest) (*ReadFileContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFileContent not implemented")
}
func (UnimplementedMasterServerServer) mustEmbedUnimplementedMasterServerServer() {}
func (UnimplementedMasterServerServer) testEmbeddedByValue()                      {}

// UnsafeMasterServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServerServer will
// result in compilation errors.
type UnsafeMasterServerServer interface {
	mustEmbedUnimplementedMasterServerServer()
}

func RegisterMasterServerServer(s grpc.ServiceRegistrar, srv MasterServerServer) {
	// If the following call panics, it indicates UnimplementedMasterServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterServer_ServiceDesc, srv)
}

func _MasterServer_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_AllocateChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).AllocateChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_AllocateChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).AllocateChunk(ctx, req.(*AllocateChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_GetFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).GetFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_GetFileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).GetFileMetadata(ctx, req.(*GetFileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_ReceiveHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).ReceiveHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_ReceiveHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).ReceiveHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_ReportInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).ReportInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_ReportInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).ReportInventory(ctx, req.(*InventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_ConfirmWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).ConfirmWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_ConfirmWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).ConfirmWrite(ctx, req.(*ConfirmWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_GetActiveMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveMasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).GetActiveMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_GetActiveMaster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).GetActiveMaster(ctx, req.(*GetActiveMasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_DeleteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).DeleteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_DeleteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).DeleteFolder(ctx, req.(*DeleteFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_MoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).MoveFile(ctx, req.(*MoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_ListFilesDetailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesDetailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).ListFilesDetailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_ListFilesDetailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).ListFilesDetailed(ctx, req.(*ListFilesDetailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServer_ReadFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServerServer).ReadFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterServer_ReadFileContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServerServer).ReadFileContent(ctx, req.(*ReadFileContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterServer_ServiceDesc is the grpc.ServiceDesc for MasterServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfspb.MasterServer",
	HandlerType: (*MasterServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFile",
			Handler:    _MasterServer_CreateFile_Handler,
		},
		{
			MethodName: "AllocateChunk",
			Handler:    _MasterServer_AllocateChunk_Handler,
		},
		{
			MethodName: "GetFileMetadata",
			Handler:    _MasterServer_GetFileMetadata_Handler,
		},
		{
			MethodName: "ReceiveHeartbeat",
			Handler:    _MasterServer_ReceiveHeartbeat_Handler,
		},
		{
			MethodName: "ReportInventory",
			Handler:    _MasterServer_ReportInventory_Handler,
		},
		{
			MethodName: "ConfirmWrite",
			Handler:    _MasterServer_ConfirmWrite_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _MasterServer_DeleteFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _MasterServer_ListFiles_Handler,
		},
		{
			MethodName: "GetActiveMaster",
			Handler:    _MasterServer_GetActiveMaster_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _MasterServer_CreateFolder_Handler,
		},
		{
			MethodName: "DeleteFolder",
			Handler:    _MasterServer_DeleteFolder_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _MasterServer_MoveFile_Handler,
		},
		{
			MethodName: "ListFilesDetailed",
			Handler:    _MasterServer_ListFilesDetailed_Handler,
		},
		{
			MethodName: "ReadFileContent",
			Handler:    _MasterServer_ReadFileContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfs.proto",
}

const (
	ChunkServer_WriteChunk_FullMethodName   = "/dfspb.ChunkServer/WriteChunk"
	ChunkServer_ReadChunk_FullMethodName    = "/dfspb.ChunkServer/ReadChunk"
	ChunkServer_ForwardChunk_FullMethodName = "/dfspb.ChunkServer/ForwardChunk"
	ChunkServer_DeleteChunks_FullMethodName = "/dfspb.ChunkServer/DeleteChunks"
)

// ChunkServerClient is the client API for ChunkServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkServerClient interface {
	WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error)
	ForwardChunk(ctx context.Context, in *ForwardChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	DeleteChunks(ctx context.Context, in *DeleteChunksRequest, opts ...grpc.CallOption) (*DeleteChunksResponse, error)
}

type chunkServerClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServerClient(cc grpc.ClientConnInterface) ChunkServerClient {
	return &chunkServerClient{cc}
}

func (c *chunkServerClient) WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServer_WriteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServer_ReadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) ForwardChunk(ctx context.Context, in *ForwardChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServer_ForwardChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) DeleteChunks(ctx context.Context, in *DeleteChunksRequest, opts ...grpc.CallOption) (*DeleteChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunksResponse)
	err := c.cc.Invoke(ctx, ChunkServer_DeleteChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServerServer is the server API for ChunkServer service.
// All implementations must embed UnimplementedChunkServerServer
// for forward compatibility.
type ChunkServerServer interface {
	WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error)
	ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error)
	ForwardChunk(context.Context, *ForwardChunkRequest) (*WriteChunkResponse, error)
	DeleteChunks(context.Context, *DeleteChunksRequest) (*DeleteChunksResponse, error)
	mustEmbedUnimplementedChunkServerServer()
}

// UnimplementedChunkServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServerServer struct{}

func (UnimplementedChunkServerServer) WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteChunk not implemented")
}
func (UnimplementedChunkServerServer) ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedChunkServerServer) ForwardChunk(context.Context, *ForwardChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardChunk not implemented")
}
func (UnimplementedChunkServerServer) DeleteChunks(context.Context, *DeleteChunksRequest) (*DeleteChunksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChunks not implemented")
}
func (UnimplementedChunkServerServer) mustEmbedUnimplementedChunkServerServer() {}
func (UnimplementedChunkServerServer) testEmbeddedByValue()                     {}

// UnsafeChunkServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServerServer will
// result in compilation errors.
type UnsafeChunkServerServer interface {
	mustEmbedUnimplementedChunkServerServer()
}

func RegisterChunkServerServer(s grpc.ServiceRegistrar, srv ChunkServerServer) {
	// If the following call panics, it indicates UnimplementedChunkServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkServer_ServiceDesc, srv)
}

func _ChunkServer_WriteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).WriteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_WriteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).WriteChunk(ctx, req.(*WriteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_ReadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).ReadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_ReadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).ReadChunk(ctx, req.(*ReadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_ForwardChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).ForwardChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_ForwardChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).ForwardChunk(ctx, req.(*ForwardChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_DeleteChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).DeleteChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServer_DeleteChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).DeleteChunks(ctx, req.(*DeleteChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkServer_ServiceDesc is the grpc.ServiceDesc for ChunkServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfspb.ChunkServer",
	HandlerType: (*ChunkServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteChunk",
			Handler:    _ChunkServer_WriteChunk_Handler,
		},
		{
			MethodName: "ReadChunk",
			Handler:    _ChunkServer_ReadChunk_Handler,
		},
		{
			MethodName: "ForwardChunk",
			Handler:    _ChunkServer_ForwardChunk_Handler,
		},
		{
			MethodName: "DeleteChunks",
			Handler:    _ChunkServer_DeleteChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfs.proto",
}

const (
	SecondaryMasterServer_ReplicateWAL_FullMethodName        = "/dfspb.SecondaryMasterServer/ReplicateWAL"
	SecondaryMasterServer_SendMasterHeartbeat_FullMethodName = "/dfspb.SecondaryMasterServer/SendMasterHeartbeat"
	SecondaryMasterServer_ApplyCheckpoint_FullMethodName     = "/dfspb.SecondaryMasterServer/ApplyCheckpoint"
	SecondaryMasterServer_RequestStateSync_FullMethodName    = "/dfspb.SecondaryMasterServer/RequestStateSync"
)

// SecondaryMasterServerClient is the client API for SecondaryMasterServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecondaryMasterServerClient interface {
	ReplicateWAL(ctx context.Context, in *ReplicateWALRequest, opts ...grpc.CallOption) (*ReplicateWALResponse, error)
	SendMasterHeartbeat(ctx context.Context, in *MasterHeartbeatRequest, opts ...grpc.CallOption) (*MasterHeartbeatResponse, error)
	ApplyCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// RequestStateSync asks the current active master to send its full state (checkpoint bytes + wal_seq + generation).
	// Used by a returning primary to catch up before re-taking the primary role.
	RequestStateSync(ctx context.Context, in *GetActiveMasterRequest, opts ...grpc.CallOption) (*CheckpointRequest, error)
}

type secondaryMasterServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSecondaryMasterServerClient(cc grpc.ClientConnInterface) SecondaryMasterServerClient {
	return &secondaryMasterServerClient{cc}
}

func (c *secondaryMasterServerClient) ReplicateWAL(ctx context.Context, in *ReplicateWALRequest, opts ...grpc.CallOption) (*ReplicateWALResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateWALResponse)
	err := c.cc.Invoke(ctx, SecondaryMasterServer_ReplicateWAL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondaryMasterServerClient) SendMasterHeartbeat(ctx context.Context, in *MasterHeartbeatRequest, opts ...grpc.CallOption) (*MasterHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterHeartbeatResponse)
	err := c.cc.Invoke(ctx, SecondaryMasterServer_SendMasterHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondaryMasterServerClient) ApplyCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, SecondaryMasterServer_ApplyCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secondaryMasterServerClient) RequestStateSync(ctx context.Context, in *GetActiveMasterRequest, opts ...grpc.CallOption) (*CheckpointRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointRequest)
	err := c.cc.Invoke(ctx, SecondaryMasterServer_RequestStateSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecondaryMasterServerServer is the server API for SecondaryMasterServer service.
// All implementations must embed UnimplementedSecondaryMasterServerServer
// for forward compatibility.
type SecondaryMasterServerServer interface {
	ReplicateWAL(context.Context, *ReplicateWALRequest) (*ReplicateWALResponse, error)
	SendMasterHeartbeat(context.Context, *MasterHeartbeatRequest) (*MasterHeartbeatResponse, error)
	ApplyCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	RequestStateSync(context.Context, *GetActiveMasterRequest) (*CheckpointRequest, error)
	mustEmbedUnimplementedSecondaryMasterServerServer()
}

// UnimplementedSecondaryMasterServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecondaryMasterServerServer struct{}

func (UnimplementedSecondaryMasterServerServer) ReplicateWAL(context.Context, *ReplicateWALRequest) (*ReplicateWALResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateWAL not implemented")
}
func (UnimplementedSecondaryMasterServerServer) SendMasterHeartbeat(context.Context, *MasterHeartbeatRequest) (*MasterHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMasterHeartbeat not implemented")
}
func (UnimplementedSecondaryMasterServerServer) ApplyCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCheckpoint not implemented")
}
func (UnimplementedSecondaryMasterServerServer) RequestStateSync(context.Context, *GetActiveMasterRequest) (*CheckpointRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestStateSync not implemented")
}
func (UnimplementedSecondaryMasterServerServer) mustEmbedUnimplementedSecondaryMasterServerServer() {}
func (UnimplementedSecondaryMasterServerServer) testEmbeddedByValue()                               {}

// UnsafeSecondaryMasterServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecondaryMasterServerServer will
// result in compilation errors.
type UnsafeSecondaryMasterServerServer interface {
	mustEmbedUnimplementedSecondaryMasterServerServer()
}

func RegisterSecondaryMasterServerServer(s grpc.ServiceRegistrar, srv SecondaryMasterServerServer) {
	// If the following call panics, it indicates UnimplementedSecondaryMasterServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecondaryMasterServer_ServiceDesc, srv)
}

func _SecondaryMasterServer_ReplicateWAL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateWALRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondaryMasterServerServer).ReplicateWAL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondaryMasterServer_ReplicateWAL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondaryMasterServerServer).ReplicateWAL(ctx, req.(*ReplicateWALRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondaryMasterServer_SendMasterHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondaryMasterServerServer).SendMasterHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondaryMasterServer_SendMasterHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondaryMasterServerServer).SendMasterHeartbeat(ctx, req.(*MasterHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondaryMasterServer_ApplyCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondaryMasterServerServer).ApplyCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondaryMasterServer_ApplyCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondaryMasterServerServer).ApplyCheckpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecondaryMasterServer_RequestStateSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveMasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondaryMasterServerServer).RequestStateSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecondaryMasterServer_RequestStateSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondaryMasterServerServer).RequestStateSync(ctx, req.(*GetActiveMasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecondaryMasterServer_ServiceDesc is the grpc.ServiceDesc for SecondaryMasterServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecondaryMasterServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfspb.SecondaryMasterServer",
	HandlerType: (*SecondaryMasterServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicateWAL",
			Handler:    _SecondaryMasterServer_ReplicateWAL_Handler,
		},
		{
			MethodName: "SendMasterHeartbeat",
			Handler:    _SecondaryMasterServer_SendMasterHeartbeat_Handler,
		},
		{
			MethodName: "ApplyCheckpoint",
			Handler:    _SecondaryMasterServer_ApplyCheckpoint_Handler,
		},
		{
			MethodName: "RequestStateSync",
			Handler:    _SecondaryMasterServer_RequestStateSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfs.proto",
}
